### ISSUE TITLE
"Kotlin - Coroutine" tag has a typo. Misses the s, they are called "Coroutines"

### ISSUE THREAD

**Issue by LouisCAD** [paug/cfp-devoxx#11]
![screen shot 2019-01-21 at 01 38 29](https://user-images.githubusercontent.com/6975237/51447343-7a064880-1d1d-11e9-88da-bd9b6799b2b3.png)

**Comment by LouisCAD** [comment]
I hope you can fix this before closing this year's CFP :)

**Comment by martinbonnin** [comment]
Thanks for the heads up! It should be fixed with more that 19 hours left to submit ;)

**Comment by LouisCAD** [comment]
The text is fixed, but now the order is wrong, as this tag is now at the end of the list.

**Comment by martinbonnin** [comment]
Ordering should be fixed with https://github.com/paug/cfp-devoxx/commit/c45f3be482d65972dd677905adac320cffe2bd2d. Fix is deploying now, should be live in a few minutes

**Comment by LouisCAD** [comment]
I can confirm that 5 hours after the "few minutes", the order is still wrong. It seems edited tags go to the end of the list.

**Comment by martinbonnin** [comment]
Yea, saw that too just before going to bed.

**Comment by martinbonnin** [comment]
Order is now fixed, 8 hours after the deadline. You can now edit your tags and witness the magnificience of a lexical sort without leading whitespace.... :unamused:

**Comment by LouisCAD** [comment]
Indeed, it's a bit late for this year 😄 
Thanks for your responsivity though, see you in April!
